### ISSUE TITLE
Images Not Resizing Since Update

### ISSUE THREAD

**Issue by PoundTown** [stolksdorf/naturalcrit#115]
**Browser Type/Version**: Google Chrome

**Operating System**: PC

**Issue Description**: Multiple attempts to adjust image size in Photoshop and Imagur fail translate to the hombrew. I opened an older homebrew created prior to the update with an image sized accordingly, then used the same image in a new homebrew from the latest update and it was a fraction of the size.

**Brew code to reproduce**:

```
http://www.naturalcrit.com/homebrew/share/BkdhWbNZ
```

**Related Images** : http://i.imgur.com/ofbH13j.png

**Comment by stolksdorf** [comment]
I didn't really touch images while building v2.

What I did add was a `width` style to the default image snippet, since many people kept asking me how to change the size of images. My gut is telling me that you haven't tried playing with the value/removed it, so it will always make your images render at 325px. 

Try tweaking/removing that and let me know if your issue persists.

**Comment by PoundTown** [comment]
After messing with it that does appear to be the issue, however the alingment snippet is missing. would it be possible to reinclude that?

**Comment by PoundTown** [comment]
I cant tinker with the image size it seems now, but im at a loss for moving it around to a different position.

**Comment by stolksdorf** [comment]
I actually split the image snippet into 2; Image and Background image. The positioning is part of the background snippet and the width is part of the regular. But all of this is just css you can google.
