### ISSUE TITLE
Render engine stops after page 2 in certain conditions

### ISSUE THREAD

**Issue by Cstulhu** [stolksdorf/naturalcrit#42]
Hey fella!

Firstly, LOVE the site, it's incredible and you have to be commended for the work. Brilliant, honestly brilliant.

I've been using it to create a class, and after finishing for some reason it won't display anything past page 2, it stops at the character table. I was wondering if you had any idea where I'm screwing your system up lol?

**Removed** is the work I've done, when I first did it it showed everything perfectly, and now it's only displaying the first 2 pages. Any suggestions? 
Many thanks!

Stuart

**Comment by stolksdorf** [comment]
Something is definitely up. Some part of your formatting is killing the rendering engine somewhere. I found a random `style` tag and removed it, but didn't fix it. I'll dive deeper later.

Also, since you pasted your edit link publicly, anyone can now edit your brew if they follow that link. I would save the text immediately and start a new one before someone deletes/change your work.

In the future only ever share your share link.

**Comment by Cstulhu** [comment]
As stated; idiot. I've saved all the text, cheers fella.

I've removed the link and saved the text, if you drop me an email I can send you the coding directly. I'm very appreciative for your help, your site really is amazing.

**Comment by stolksdorf** [comment]
haha, no worries. I was just scared you'd lose your work (I quickly made a back-up for you, just in case). 

I'll ping you when I start working on this bug, but that might be a while.

**Comment by Cstulhu** [comment]
That's great, I need to do work on the front page with some artwork bledning anyhow. Thanks again!

**Comment by stolksdorf** [comment]
I believe this should be fixed in v1.4, please reopen if you experience this again.
