### ISSUE TITLE
Implement code mirror editor for markdown

### ISSUE THREAD

**Issue by sskieller** [stolksdorf/naturalcrit#52]
**Browser Type/Version:** Google Chrome: Version 48.0.2564.116 m (64-bit)

**Operating System:** Windows 10

**Idea:** Could you make it easier to read the code for editing?
Either by adding background colors for tables, non-tables, char sheets, monster stat blocks and so forth, or coloring of the text. I sometimes have a hard time finding the right spot in the text, with no difference in the text.

**Comment by SecretShop** [comment]
Alright so i am not the creator, but just for a quick point... The beauty of markdown is in fact its lack of styling and simplicity. I have no idea what can and can not be implemented to ease readability, but maybe instead of the markdown being changed, being able to click on the preview and for that to take you to that code snippet might be nice.

**Comment by stolksdorf** [comment]
I think updating the current editor to something nicer that supports Markdown syntax highlighting would be a nice feature. I'm going to update the title of this issue to reflect that. Thanks for the suggestion!

**Comment by stolksdorf** [comment]
Finally got around to doing this. Took me long enough. This will be released in v2, which is currently being tested.
