### ISSUE TITLE
Background-free Option

### ISSUE THREAD

**Issue by Tsurumah** [stolksdorf/NaturalCrit#6]
For clarity, when I make homebrew, I don't include the background, so I'd like to request a toggle background on/off button, if possible.

**Comment by qaeta** [comment]
As a work around, you could simply add your own blank background image to cover up the default one. At least until there is an option to replace it.

**Comment by Tsurumah** [comment]
Good point, actually; I've also noticed that the background, when adding new pages, doesn't flip to have the footer frame facing the opposite direction.

**Comment by Qaeta** [comment]
Ah, you are correct, should probably put it in a new issue though, easier to track when developing.

**Comment by Qaeta** [comment]
This actually should not be a bug. Since Homebrew has HTML support, if you put the following at the top of your homebrew:

<code>
<style>
.phb {
    background-image: none;
    background-color: #FFF;
}
</style>
</code>

then it will do what you wanted.

**Comment by Tsurumah** [comment]
Awesome. Didn't even think about that, and I feel like an idiot for not doing so. Now it appears that the footer is already a separate element, so my flipping suggestion still applies, yes?

**Comment by Qaeta** [comment]
Yes it would. The issue with the footer element, is that it pretty much needs to be done programatically, as it needs to automatically alternate when adding pages. Even if you found an identifier for the element, it would still flip ALL of them, instead of every other one.

**Comment by stolksdorf** [comment]
I added a 'Printer Friendly' snippet that inject css code into your brew that will fix this issue easily for all users. It changes the backgrounds to white and hides images. I like keeping this controlled via code, rather than another UI, just incase users want to tweak it further, such as adding a [greyscale filter](https://css-tricks.com/almanac/properties/f/filter/).

Side note: I implemented the footer flip using just CSS, `:nth-child(odd)`. You have probably already seen that though.
